# Generated by Django 4.0.5 on 2022-06-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
